version: '3'
services:

  ### Memcached ###
  memcached:
    image: memcached:bullseye
    command: memcached
    ports:
      - "11211:11211"

  ### MongoDB ###
  mongodb:
    image: mongo:latest
    command: mongod
    ports:
      - "27017:27017"

  ### Redis ###
  redis:
    image: redis:bullseye
    command: redis-server
    ports:
      - "6379:6379"

  ### Valkey ###
  valkey:
    image: valkey/valkey:7.2
    command: valkey-server
    ports:
      - "6380:6379"
